.TH GMTP 1 "September 09, 2010"
.SH NAME
gmtp \- simple MP3 player client for MTP based devices
.SH SYNOPSIS
.B gmtp
.br
.SH DESCRIPTION
.B gMTP
is a simple and light-weight interface to the features provided
by libmtp, which allows users to manage the files stored on any MTP
music player supported by the libraries, including those with
multiple storage devices (e.g. mobile phones).
.PP
.B gMTP
has been written with GTK+ libraries, and after the installation the
application is available from the
.B Applications
menu. 
.br
.SH AUTHOR
gmtp was written by Darran Kartaschew <chewy509@mailcity.com>.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>,
for the Debian project (but may be used by others).
